TicketBookingOnline.Web/Areas/Admin/Controllers/KhachHangController.cs
using Microsoft.AspNetCore.Mvc;
using TicketBookingOnline.Web.IServices;

namespace TicketBookingOnline.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class KhachHangController : BaseController
    {
        private readonly IKhachHangServices _khachHangServices;
        private readonly IVeServices _veServices;

        public KhachHangController(IKhachHangServices khachHangServices, IVeServices veServices)
        {
            _khachHangServices = khachHangServices;
            _veServices = veServices;
        }

        public async Task<IActionResult> Index(int? cumRapId, string tenKhachHang, string soDienThoai, string diaChiKhachHang,
            string emailKhachHang, int index = 1)
        {
            if (HttpContext.Session.GetString("CumRapId") != null)
            {
                cumRapId = Int32.Parse(HttpContext.Session.GetString("CumRapId"));
            }

            var khachHangs = await _khachHangServices.FilterWithRowPerPageAsync(index, cumRapId, tenKhachHang, soDienThoai, diaChiKhachHang,
                emailKhachHang, StaticDetails.KhachHangAPIPath + "FilterWithRowPerPage");
            int count = 0;
            count = await _khachHangServices.CountKhachHangFilterAsync(cumRapId, tenKhachHang, soDienThoai, diaChiKhachHang,
                emailKhachHang, StaticDetails.KhachHangAPIPath + "CountKhachHangFilter");
            ViewBag.Page = index;
            ViewBag.MaxPage = (count / 20) - (count % 20 == 0 ? 1 : 0);
            ViewBag.CumRapId = cumRapId;
            ViewBag.TenKhachHang = tenKhachHang;
            ViewBag.SoDienThoai = soDienThoai;
            ViewBag.DiaChi = diaChiKhachHang;
            ViewBag.Email = emailKhachHang;
            return View(khachHangs);
        }

        public async Task<IActionResult> Transaction(int id)
        {
            var khachHang = await _khachHangServices.GetByIdAsync(id, StaticDetails.KhachHangAPIPath + "GetById");
            ViewBag.KhachHang = khachHang;
            var transactions = await _veServices.GetVeByKhachHangIdAsync(id, StaticDetails.VeAPIPath + "GetVeByKhachHangId");
            return View(transactions);
        }

        public async Task<IActionResult> TransactionDetails(int veId)
        {
            var ve = await _veServices.GetByIdAsync(veId, StaticDetails.VeAPIPath + "GetById");
            return View(ve);
        }
    }
}

TicketBookingOnline.Web/Areas/Admin/Views/KhachHang/Index.cshtml
@model IEnumerable<KhachHangViewModel>

@{
    ViewData["Title"] = "Index";
    var nextPage = (int)ViewBag.Page + 1;
    var prevPage = (int)ViewBag.Page - 1 < 0 ? 1 : (int)ViewBag.Page - 1;
    var disableNext = Model.ToList().Count() < 20 ? "disable" : "";
    var disablePrev = (int)ViewBag.Page == 1 ? "disable" : "";
}

<h1>Danh sách khách hàng</h1>
<hr /> 
<form asp-action="Index" method="post" style="margin-top:10px; margin-right:20%">
        <div class="row">

            <div class="col-sm-12 col-md-6 col-lg-6">
                <input id="tenKhachHang" name="tenKhachHang" class="form-control" placeholder="Nhập tên khách hàng" style="width:60%" value="@ViewBag.TenKhachHang" />
                <br>
                <input id="soDienThoai" name="soDienThoai" class="form-control" placeholder="Nhập số điện thoại " style="width:60%" value="@ViewBag.SoDienThoai"/>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-6">
                <input id="emailKhachHang" name="emailKhachHang" class="form-control" placeholder="Nhập email " style="width:60%" value="@ViewBag.DiaChi"/>
                <br>
                <input id="diaChiKhachHang" name="diaChiKhachHang" class="form-control" placeholder="Nhập địa chỉ" style="width:60%" value="@ViewBag.Email"/>
            </div>
            <div class="form-group">
                <input type="submit" value="Tìm kiếm" class="btn btn-info" style="float:right; margin-right:6%" />
            </div>
        </div>
    </form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HoTen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiemThuong)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoDienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiemThuong)
            </td>
            <td>
                <a asp-action="Transaction" asp-route-id="@item.UserId">Giao dịch</a>
            </td>
        </tr>
}
    </tbody>
</table>
<div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
     <div class="btn-group mr-2" role="group" aria-label="First group">
         <a class="prev @disablePrev btn btn-white btn-white-group" style="border:0.6px solid green" 
         asp-controller="KhachHang" asp-action="Index" asp-route-tenKhachHang="@ViewBag.TenKhachHang"
         asp-route-soDienThoai="@ViewBag.SoDienThoai" asp-route-diaChiKhachHang="@ViewBag.DiaChi"
         asp-route-emailKhachHang="@ViewBag.Email" asp-route-index="@prevPage">&laquo;</a>

     </div>
     <div class="btn-group mr-2" role="group" aria-label="Second group">
         @for (int i = 1; i <= ViewBag.MaxPage + 1; i++)
         {
            if(@ViewBag.Page == i)
            {
                <a class="btn btn-white mr-2 btn-white-group activePage" style="border:0.6px solid green" 
             asp-controller="KhachHang" asp-action="Index" asp-route-tenKhachHang="@ViewBag.TenKhachHang"
            asp-route-soDienThoai="@ViewBag.SoDienThoai" asp-route-diaChiKhachHang="@ViewBag.DiaChi"
            asp-route-emailKhachHang="@ViewBag.Email" asp-route-index="@i">@i </a>
            }
            else
            {
                <a class="btn btn-white mr-2 btn-white-group" style="border:0.6px solid green" 
             asp-controller="KhachHang" asp-action="Index" asp-route-tenKhachHang="@ViewBag.TenKhachHang"
            asp-route-soDienThoai="@ViewBag.SoDienThoai" asp-route-diaChiKhachHang="@ViewBag.DiaChi"
            asp-route-emailKhachHang="@ViewBag.Email" asp-route-index="@i">@i </a>
            }
            
         }
     </div>
     <div class="btn-group" role="group" aria-label="Third group">
         <a class="next @disableNext btn btn-white btn-white-group" style="border:0.6px solid green" 
         asp-controller="KhachHang" asp-action="Index" asp-route-tenKhachHang="@ViewBag.TenKhachHang"
         asp-route-soDienThoai="@ViewBag.SoDienThoai" asp-route-diaChiKhachHang="@ViewBag.DiaChi"
         asp-route-emailKhachHang="@ViewBag.Email" asp-route-index="@nextPage">&raquo;</a>
     </div>
 </div>

TicketBookingOnline.Web/Areas/Admin/Views/KhachHang/Transaction.cshtml
@model IEnumerable<VeViewModel>

@{
    ViewData["Title"] = "Index";
}
<h1>Lịch sử giao dịch</h1>
<hr />
<div class="row">
    <p><b>Họ và tên khách hàng: </b>@ViewBag.KhachHang.HoTen</p>
    <p><b>Số điện thoại: </b>@ViewBag.KhachHang.SoDienThoai</p>
    <p><b>Email: </b>@ViewBag.KhachHang.Email</p>
    <p><b>Địa chỉ: </b>@ViewBag.KhachHang.DiaChi</p>
</div>
@if (Model == null)
{
    <h1>Không có vé nào được đặt</h1>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th width=25%>
                    @Html.DisplayNameFor(model => model.LichChieu.Phim.TenPhim)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LichChieu.XuatChieu)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TongGiaVe)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TrangThai)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width=25%>
                        @Html.DisplayFor(modelItem => item.LichChieu.Phim.TenPhim)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LichChieu.XuatChieu)
                    </td>
                    <td>
                        @{
                            string tongGiaVe = @String.Format("{0:0,0}", @item.TongGiaVe);
                        }
                        @Html.DisplayFor(modelItem => tongGiaVe)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TrangThai)
                    </td>
                    <td>
                        <a asp-action="TransactionDetails" asp-route-veId="@item.VeId">Chi tiết</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<div>
    <a asp-action="Index" class="btn btn-info">Trở về</a>
</div>

TicketBookingOnline.Web/Areas/Admin/Views/KhachHang/TransactionDetails.cshtml
@model VeDetailViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Thông tin chi tiết vé</h1>
<hr />
<div>
    <div class="row">
        <p><b>Họ và tên khách hàng: </b>@Model.User.HoTen</p>
        <p><b>Số điện thoại: </b>@Model.User.SoDienThoai</p>
    </div>
    <div class="row">
        <input asp-for="VeId" class="form-control" hidden />
        <div class="col-4">
            <img src="~/posters/@Model.LichChieu.Phim.Anh" width=80% height=100% />
        </div>
        <div class="col-8">
            <h2>@Model.LichChieu.Phim.TenPhim</h2>
            <p><b>Thời lượng: </b>@Model.LichChieu.Phim.ThoiLuong phút</p>
            <p><b>Xuất chiếu: </b>@Model.LichChieu.XuatChieu</p>
             <p><b>Vị trí: </b></p>
                    @foreach(var item in @Model.ChiTietVes){
                        <span>@item.ViTri &nbsp</span>
                    }   
            <p><b>Khuyến mãi: @Model.LichChieu.PhanTramKM (%)</b></p>
            <h3><b style="color:red">Tổng giá vé: @String.Format("{0:0,0}", @Model.TongGiaVe) VNĐ</b></h3>
            
        </div>
    </div>
</div>
<br />
<div style="margin-top:20px">
    <a asp-area="Admin" asp-controller="KhachHang" asp-action="Transaction" asp-route-id="@Model.User.UserId" class="btn btn-info">Trở về</a>
</div>