TicketBookingOnline.Web/Areas/Admin/Controllers/CumRapController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TicketBookingOnline.ViewModels.CumRaps;
using TicketBookingOnline.ViewModels.Raps;
using TicketBookingOnline.Web.IServices;

namespace TicketBookingOnline.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CumRapController : BaseController
    {
        private readonly ICumRapServices _cumRapServices;
        private readonly IRapServices _rapServices;
        private readonly IThanhPhoServices _thanhPhoServices;

        public CumRapController(ICumRapServices cumRapServices, IRapServices rapServices, IThanhPhoServices 
            thanhPhoServices)
        {

            _cumRapServices = cumRapServices;
            _rapServices = rapServices;
            _thanhPhoServices = thanhPhoServices;
        }
        public async Task<IActionResult> Index(string tenCumRap, int thanhPhoId, int index = 1)
        {
            var thanhPhos = await _thanhPhoServices.GetAllAsync(StaticDetails.ThanhPhoAPIPath + "GetAll");
            ViewBag.ThanhPho = new SelectList(thanhPhos, "ThanhPhoId", "TenThanhPho");
            var cumRaps = await _cumRapServices.GetWithRowPerPageAsync(index, tenCumRap, thanhPhoId, StaticDetails.CumRapAPIPath + "GetWithRowPerPage");
            int count = 0;
            count = await _cumRapServices.CountAllAsync(tenCumRap, thanhPhoId, StaticDetails.CumRapAPIPath + "CountAll");
            ViewBag.Page = index;
            ViewBag.MaxPage = (count / 20) - (count % 20 == 0 ? 1 : 0);
            ViewBag.TenCumRap = tenCumRap;
            ViewBag.ThanhPhoId = thanhPhoId;
            return View(cumRaps);
        }

        public async Task<IActionResult> Details(int cumRapId)
        {
            var raps = await _rapServices.GetRapByCumRapIdAsync(cumRapId, StaticDetails.RapAPIPath + "GetRapByCumRapId");
            var cumRap = await _cumRapServices.GetByIdAsync(cumRapId, StaticDetails.CumRapAPIPath + "GetById");
            ViewBag.CumRap = cumRap;
            return View(raps);
        }

        public async Task<IActionResult> CreateRap(int createCumRapId, string tenRap, string loaiRap)
        {
            var rapVM = new RapViewModel();
            rapVM.CumRapId = createCumRapId;
            rapVM.TenRap = tenRap;
            rapVM.LoaiRap = loaiRap;
            var response = await _rapServices.CreateAsync(rapVM, StaticDetails.RapAPIPath + "Create");
            if (response)
            {
                TempData["Success"] = "Thêm mới thành công !";
            }
            else
            {
                TempData["Error"] = "Đã xảy ra lỗi !";
            }
            return RedirectToAction("Details", "CumRap", new { cumRapId = createCumRapId });
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var thanhPhos = await _thanhPhoServices.GetAllAsync(StaticDetails.ThanhPhoAPIPath + "GetAll");
            ViewBag.ThanhPho = new SelectList(thanhPhos, "ThanhPhoId", "TenThanhPho");
            //ViewData["ThanhPho"] = new SelectList(thanhPhos, "ThanhPhoId", "TenThanhPho");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCumRapViewModel cumRapVM)
        {
            var response = await _cumRapServices.CreateAsync(cumRapVM, StaticDetails.CumRapAPIPath + "Create");
            if (response)
            {
                TempData["Success"] = "Thêm mới thành công !";
            }
            else
            {
                TempData["Error"] = "Đã xảy ra lỗi !";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCumRap(int cumRapId, string tenRap, string diaChi, string soDienThoai)
        {
            var cumRapVM = new CreateCumRapViewModel();
            cumRapVM.CumRapId = cumRapId;
            cumRapVM.TenRap = tenRap;
            cumRapVM.DiaChi = diaChi;
            cumRapVM.SoDienThoai = soDienThoai;
            var response = await _cumRapServices.UpdateAsync(cumRapVM, StaticDetails.CumRapAPIPath + "Update");
            if (response)
            {
                TempData["Success"] = "Cập nhật thành công !";
            }
            else
            {
                TempData["Error"] = "Đã xảy ra lỗi !";
            }
            return RedirectToAction("Details", "CumRap", new { cumRapId = cumRapId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCumRap(int cumRapId)
        {
            var response = await _cumRapServices.DeleteAsync(cumRapId, StaticDetails.CumRapAPIPath + "Delete");
            if (response)
            {
                TempData["Success"] = "Xóa thành công !";
            }
            else
            {
                TempData["Error"] = "Đã xảy ra lỗi !";
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteRap(int rapId, int cumId)
        {
            var response = await _rapServices.DeleteAsync(rapId, StaticDetails.RapAPIPath + "Delete");
            if (response)
            {
                TempData["Success"] = "Xóa thành công !";
            }
            else
            {
                TempData["Error"] = "Đã xảy ra lỗi !";
            }
            return RedirectToAction("Details", "CumRap", new { cumRapId = cumId });
        }
    }
}

TicketBookingOnline.Web/Areas/Admin/Controllers/RapController.cs
using Microsoft.AspNetCore.Mvc;
using TicketBookingOnline.ViewModels.RapGhes;
using TicketBookingOnline.ViewModels.Raps;
using TicketBookingOnline.Web.IServices;

namespace TicketBookingOnline.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RapController : BaseController
    {
        private readonly IRapServices _rapServices;
        private readonly IRapGheServices _rapGheServices;

        public RapController(IRapServices rapServices, IRapGheServices rapGheServices)
        {
            _rapServices = rapServices;
            _rapGheServices = rapGheServices;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            int cumRapId = int.Parse(HttpContext.Session.GetString("CumRapId"));
            var raps = await _rapServices.GetRapByCumRapIdAsync(cumRapId, StaticDetails.RapAPIPath + "GetRapByCumRapId");
            return View(raps);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int rapId, int cumRapId)
        {
            ViewBag.CumRapId = cumRapId;
            var rap = await _rapServices.GetRapByIdAsync(rapId, StaticDetails.RapAPIPath + "GetRapById");
            ViewBag.Rap = rap;
            var rapGhes = await _rapGheServices.GetRapGheByRapAsync(rapId, StaticDetails.RapGheAPIPath + "GetRapGheByRap");
            foreach(var item in rapGhes)
            {
                item.RapId = rapId;
            }
            return View(rapGhes.AsQueryable().ToList());
        }

        [HttpPost]
        public async Task<IActionResult> Edit(List<RapGheViewModel> rapGhes, string loaiRap, int rapId)
        {
            var rapUpdate = new RapViewModel();
            rapUpdate.RapId = rapId;
            rapUpdate.LoaiRap = loaiRap;
            var response1 = await _rapServices.UpdateAsync(rapUpdate, StaticDetails.RapAPIPath + "Update");
            var response2 = await _rapGheServices.UpdateRange(rapGhes, StaticDetails.RapGheAPIPath + "UpdateRange");
            if (response1 && response2)
            {
                TempData["Success"] = "Cập nhật thành công !";
                return RedirectToAction(nameof(Edit), new { rapId = rapId});
            }
            var rap = await _rapServices.GetRapByIdAsync(rapId, StaticDetails.RapAPIPath + "GetRapById");
            ViewBag.Rap = rap;
            TempData["Error"] = "Đã xảy ra lỗi!";
            return View(rapGhes);
        }
    }
}

TicketBookingOnline.Web/Areas/Admin/Views/CumRap/Create.cshtml
@model CreateCumRapViewModel

@{
    ViewData["Title"] = "CreateCumRap";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<h1>Thêm mới cụm rạp</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TenRap" class="control-label"></label>
                <input asp-for="TenRap" class="form-control" />
                <span asp-validation-for="TenRap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Thành phố</label>
                <select asp-for="ThanhPhoId" class="form-control" asp-items="@ViewBag.ThanhPho"></select>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label"></label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoDienThoai" class="control-label"></label>
                <input asp-for="SoDienThoai" class="form-control" />
                <span asp-validation-for="SoDienThoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Thêm mới" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-info">Trở về</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TicketBookingOnline.Web/Areas/Admin/Views/CumRap/Details.cshtml
@model IEnumerable<RapViewModel>

@{
    Layout = "_AdminLayout";
    ViewData["Title"] = "Index";
}

<h1>@ViewBag.CumRap.TenRap</h1>
<hr />
<form asp-action="UpdateCumRap" method="post">
    <div class="row">
        <input id="cumRapId" name="cumRapId" value="@ViewBag.CumRap.CumRapId" hidden />
        <input id="tenRap" name="tenRap" value="@ViewBag.CumRap.TenRap" hidden />
        <div class="col-7">
            <label class="control-label">Địa chỉ :</label>
            <input id="diaChi" name="diaChi" value="@ViewBag.CumRap.DiaChi" class="form-control" required />
        </div>
        <div class="col-3">
            <label class="control-label">Số điện thoại :</label>
            <input id="soDienThoai" name="soDienThoai" value="@ViewBag.CumRap.SoDienThoai" class="form-control" required />
        </div>
        <div class="col-2">
            <input type="submit" class="btn  btn-primary" value="Cập nhật" style="margin-top: 25px"/>
        </div>       
    </div>    
</form>
<hr />
<p>
    <button type="button" class="btn  btn-primary" data-toggle="modal" data-target="#myModal"
            onclick="document.getElementById('createCumRapId').value=@ViewBag.CumRap.CumRapId">
        Thêm mới
    </button>
</p>
<table class="table">
    <thead>
        <tr>
            <th width=30%>
                @Html.DisplayNameFor(model => model.TenRap)
            </th width=50%>
            <th>
                @Html.DisplayNameFor(model => model.LoaiRap)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width=30%>
                    @Html.DisplayFor(modelItem => item.TenRap)
                </td>
                <td width=50%>
                    @Html.DisplayFor(modelItem => item.LoaiRap)
                </td>
                <td>
                    <a asp-controller="Rap" asp-action="Edit" asp-route-rapId="@item.RapId" asp-route-cumRapId="@ViewBag.CumRap.CumRapId">Chi tiết</a>|
                    <a href="" data-toggle="modal" data-target="#modalDelete"
                        onclick="document.getElementById('rapId').value=@item.RapId,
                            document.getElementById('cumId').value=@ViewBag.CumRap.CumRapId">
                        Xóa
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal Create -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <form asp-controller="CumRap" asp-action="CreateRap" method="post">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-body">
                    <h2 class="modal-title" style="float: left"><b>Thêm rạp mới</b></h2>
                    <button type="button" style="float: right" class="close" data-dismiss="modal">&times;</button>
                    <hr />
                    <input name="createCumRapId" id="createCumRapId" class="form-control" />
                    <div class="form-group">
                        <label class="form-label">Tên rạp</label>
                        <input id="tenRap" name="tenRap" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label class="form-label">Loại rạp</label>
                        <select id="loaiRap" name="loaiRap" class="form-select form-control">
                            <option value="Rạp 2D">Rạp 2D</option>
                            <option value="Rạp 3D">Rạp 3D</option>
                            <option value="Rạp 4D">Rạp 4D</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" value="Create" class="btn  btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>

<!-- Modal Delete -->
<div class="modal fade" id="modalDelete" role="dialog">
    <div class="modal-dialog">
        <form asp-controller="CumRap" asp-action="DeleteRap" method="post">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-body">
                    <h4 class="modal-title" style="float: left">Delete Confirm</h4>
                    <button type="button" style="float: right" class="close" data-dismiss="modal">&times;</button>
                    <hr />
                    <h3>Are you sure want to delete ?</h3>
                    <input name="cumId" id="cumId" class="form-control" />
                    <input name="rapId" id="rapId" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index" class="btn btn-info">Trở về</a>
</div>

TicketBookingOnline.Web/Areas/Admin/Views/CumRap/Index.cshtml
@model IEnumerable<CumRapViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    var nextPage = (int)ViewBag.Page + 1;
    var prevPage = (int)ViewBag.Page - 1 < 0 ? 1 : (int)ViewBag.Page - 1;
    var disableNext = Model.ToList().Count() < 20 ? "disable" : "";
    var disablePrev = (int)ViewBag.Page == 1 ? "disable" : "";
}

<h1>Danh sách rạp CGV</h1>
<hr />
<p>
    <a asp-action="Create" class="btn  btn-primary">Thêm mới</a>
</p>
<form asp-action="Index" method="post">
    <div class="row">
        <div class="col-4">
            <label class="control-label">Tìm kiếm</label>
            <input type="text" name="tenCumRap" class="form-control" placeholder="Nhập tên cụm rạp..." />
        </div>
        <div class="col-6">
            <label class="control-label">Chọn thành phố</label>
            <select name="thanhPhoId" class="form-control" asp-items="@ViewBag.ThanhPho">
                <option selected="selected" value="">- Chọn thành phố -</option>
            </select>
        </div>
        <div class="col-2">
            <input type="submit" value="Tìm kiếm" style="margin-top: 25px" class="btn btn-info form-control" />
        </div>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ThanhPho.TenThanhPho)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenRap)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaChi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoDienThoai)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width=15%>
                    @Html.DisplayFor(modelItem => item.ThanhPho.TenThanhPho)
                </td>
                <td width=20%>
                    @Html.DisplayFor(modelItem => item.TenRap)
                </td>
                <td width=30%>
                    @Html.DisplayFor(modelItem => item.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SoDienThoai)
                </td>
                @*<td>
                    <a asp-action="Details" asp-route-cumRapId="@item.CumRapId">Chi tiết</a>
                    <a href="" class="open" data-toggle="modal" data-target="#modalDelete"
                    onclick="document.getElementById('cumRapId').value=@item.CumRapId">Xóa</a>
                    </td>*@
                <td>
                    <a class="nav-link text-muted waves-effect waves-dark pro-pic" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-pen" style="font-size: x-large; color: darkcyan"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end user-dd animated" aria-labelledby="navbarDropdown" style="left: -100px">

                        <li>
                            <a asp-action="Details" asp-route-cumRapId="@item.CumRapId"><i class="fa-solid fa-file-lines"></i>&nbsp Chi tiết</a>
                        </li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <a href="" class="open" data-toggle="modal" data-target="#modalDelete"
                           onclick="document.getElementById('cumRapId').value=@item.CumRapId"><i class="fa-solid fa-trash"></i>&nbsp Xóa</a>
                        </li>
                    </ul>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group mr-2" role="group" aria-label="First group">
        <a class="prev @disablePrev btn btn-white btn-white-group" style="border:0.6px solid green"
           asp-controller="CumRap" asp-action="Index" asp-route-tenCumRap="@ViewBag.TenCumRap"
           asp-route-thanhPhoId="@ViewBag.ThanhPhoId" asp-route-index="@prevPage">&laquo;</a>

    </div>
    <div class="btn-group mr-2" role="group" aria-label="Second group">
        @for (int i = 1; i <= ViewBag.MaxPage + 1; i++)
        {
            if(@ViewBag.Page == i){
                <a class="btn btn-white mr-2 btn-white-group activePage" style="border:0.6px solid green"
               asp-controller="CumRap" asp-action="Index" asp-route-tenCumRap="@ViewBag.TenCumRap"
               asp-route-thanhPhoId="@ViewBag.ThanhPhoId" asp-route-index="@i">@i </a>
            }
            else
            {
                <a class="btn btn-white mr-2 btn-white-group" style="border:0.6px solid green"
               asp-controller="CumRap" asp-action="Index" asp-route-tenCumRap="@ViewBag.TenCumRap"
               asp-route-thanhPhoId="@ViewBag.ThanhPhoId" asp-route-index="@i">@i </a>
            }            
        }
    </div>
    <div class="btn-group" role="group" aria-label="Third group">
        <a class="next @disableNext btn btn-white btn-white-group" style="border:0.6px solid green"
           asp-controller="CumRap" asp-action="Index" asp-route-tenCumRap="@ViewBag.TenCumRap"
           asp-route-thanhPhoId="@ViewBag.ThanhPhoId" asp-route-index="@nextPage">&raquo;</a>
    </div>
</div>


<!-- Modal Delete -->
<div class="modal fade" id="modalDelete" role="dialog">
    <div class="modal-dialog">
        <form asp-action="DeleteCumRap" method="post">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-body">
                    <h4 class="modal-title" style="float: left">Xác nhận xóa</h4>
                    <button type="button" style="float: right" class="close" data-dismiss="modal">&times;</button>
                    <hr />
                    <h3>Bạn chắc chắn muốn xóa cụm rạp này ?</h3>
                    <input name="cumRapId" id="cumRapId" hidden />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>