TicketBookingOnline.Web/Controllers/KhuyenMaiController.cs
using Microsoft.AspNetCore.Mvc;
using TicketBookingOnline.Web.IServices;

namespace TicketBookingOnline.Web.Controllers
{
    public class KhuyenMaiController : Controller
    {
        private readonly IPhimServices _phimServices;
        public KhuyenMaiController(IPhimServices phimServices)
        {
            _phimServices = phimServices;
        }

        public async Task<IActionResult> Index(int index = 1)
        {
            ViewBag.Page = index;
            var phimKhuyenMais = await _phimServices.KhuyenMaiPhimAsync(index, StaticDetails.PhimAPIPath + "KhuyenMaiPhim");
            var count = await _phimServices.CountKhuyenMaiPhim(StaticDetails.PhimAPIPath + "CountKhuyenMaiPhim");
            ViewBag.MaxPage = (count /8 -(count % 8 == 0 ? 1 : 0));
            return View(phimKhuyenMais);

        }
    }
}

TicketBookingOnline.Web/Controllers/PhimController.cs
using Microsoft.AspNetCore.Mvc;
using TicketBookingOnline.ViewModels.Comments;
using TicketBookingOnline.Web.IServices;

namespace TicketBookingOnline.Web.Controllers
{
    public class PhimController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPhimServices _phimServices;

        private readonly ICumRapServices _cumRapServices;
        private readonly ILichChieuServices _lichChieuServices;
        private readonly ICommentServices _commentServices;

        public PhimController(IPhimServices phimServices, ICumRapServices cumRapServices,
            ILogger<HomeController> logger, ILichChieuServices lichChieuServices, ICommentServices commentServices)
        {
            _logger = logger;
            _phimServices = phimServices;
            _cumRapServices = cumRapServices;
            _lichChieuServices = lichChieuServices;
            _commentServices = commentServices;
        }

        public async Task<IActionResult> ChiTietPhim(int phimId)
        {
            
            var phim = await _phimServices.GetPhimById(phimId,StaticDetails.PhimAPIPath + "GetPhimById");
            var phimLienQuan = await _phimServices.GetPhimLienQuanAsync(phimId, StaticDetails.PhimAPIPath + "PhimLienQuan");
            ViewBag.PhimLienQuan = phimLienQuan.ToList();
            return View(phim);
        }

        public async Task<IActionResult> Phim(int phimId)
        {
           
            var phim = await _phimServices.GetPhimById(phimId, StaticDetails.PhimAPIPath + "GetPhimByTrangThaiRowPerPage");

            return View(phim);
        }

        public async Task<JsonResult> AddComment(string CommentText, int PhimId)
        {
            var newComment = new CreateCommentViewModel()
            {
                UserId = int.Parse(HttpContext.Session.GetString("KhachHangId")),
                NoiDung = CommentText,
                PhimId = PhimId
            };
            var comment = await _commentServices.CreateAsync(newComment, StaticDetails.CommentAPIPath + "Create");
            return Json(comment);
        }
    }
}

TicketBookingOnline.Web/Views/KhuyenMai/Index.cshtml
@model IEnumerable<PhimViewModel>

@{
    ViewData["Title"] = "Khuyến mãi - CGV";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{

    var nextPage = (int)ViewBag.Page + 1;
    var prevPage = (int)ViewBag.Page - 1 < 0 ? 1 : (int)ViewBag.Page - 1;
    var disableNext = Model.ToList().Count() < 8 ? "disable" : "";
    var disablePrev = (int)ViewBag.Page == 1 ? "disable" : "";
}

<div class="container" style="margin-top: 150px; margin-bottom: 70px">
    @if ((int)ViewBag.MaxPage == -1)
    {
        <h5 class="alert alert-danger">
            <i class="fa-solid fa-triangle-exclamation"></i> &nbsp;
            Rất tiếc hiện tại không có phim nào được khuyến mãi
        </h5>
    }
    else
    {
        <div class="tab">
            <div class="section-header-2">
                <div class="left" style="width: 1000px">
                    <h2 class="title">Khuyến mãi</h2>
                    <p>Hãy chắc chắn không bỏ lỡ những khuyến mãi hấp dẫn chỉ có tại CGV</p>
                </div>
            </div>
        </div>

        <div class="tab-area mb-30-none">
            <div class="tab-item active">
                <div class="row mb-10 justify-content-center">

                    @foreach (var item in Model)
                    {
                        @*<--item-->*@
                        <div class="col-sm-6 col-lg-3">
                            <div class="movie-grid">
                                <div style="position:relative;z-index: 10;">
                                    <sapn style="margin-top:15px;padding:10px; background:red; color:white; font-size:25px">@item.KhuyenMai%</sapn>
                                </div>
                                <div class="movie-thumb c-thumb" style="margin-top: -50px;">
                                    <a asp-controller="Phim" asp-action="ChiTietPhim" asp-route-phimId="@item.PhimId">
                                        <img src="~/posters/@item.Anh" alt="movie" height="300px">
                                    </a>
                                </div>
                                <div class="movie-content bg-one">
                                    <h5 class="title m-0">
                                        <a asp-controller="Phim" asp-action="ChiTietPhim" asp-route-phimId="@item.PhimId">@item.TenPhim</a>
                                        <p style="font-size:13px;padding: 16px 0 0 0;">Thể Loại: @item.TheLoais</p>
                                        <p style="font-size:13px;">Thời lượng: @item.ThoiLuong phút</p>
                                        <p style="font-size:13px;">Khởi chiếu: @item.KhoiChieu.ToShortDateString()</p>
                                    </h5>

                                </div>
                            </div>
                        </div>

                    }
                    <div class="pagination-area text-center">
                            @foreach (var item in Model)
                            {
                                <a class="@disablePrev" asp-controller="KhuyenMai" asp-action="Index" asp-route-index="@prevPage"><i class="fas fa-angle-double-left"></i><span>Prev</span></a>
                                @for (int i = 1; i <= ViewBag.MaxPage + 1; i++)
                                {
                                    if(ViewBag.Page == i)
                                    {
                                        <a asp-controller="KhuyenMai" asp-action="Index" asp-route-index="@i" class="active">@i </a>
                                    }
                                    else
                                    {
                                        <a asp-controller="KhuyenMai" asp-action="Index" asp-route-index="@i">@i </a>
                                    }
                                }

                                <a class="@disableNext"  asp-controller="KhuyenMai" asp-action="Index" asp-route-index="@nextPage"><span>Next</span><i class="fas fa-angle-double-right"></i></a>
                                break;
                            }
                        </div>
                </div>
            </div>
        </div>
    }
</div>

 <partial name="_PhimHot"/>