TicketBookingOnline.Web/Areas/Admin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Mvc;
using TicketBookingOnline.Core.Models;
using TicketBookingOnline.ViewModels.Sliders;
using TicketBookingOnline.Web.IServices;

namespace TicketBookingOnline.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly ISliderServices _sliderServices;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public SliderController(ISliderServices SliderServices, IWebHostEnvironment webHostEnvironment)
        {
            _sliderServices = SliderServices;
            _webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            var sliders = await _sliderServices.GetAllAsync(StaticDetails.SliderAPIPath + "GetAll");
            return View(sliders);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(SliderViewModel slider, IFormFile anhFile)
        {
            if (anhFile != null)
            {
                string SliderFolder = Path.Combine(_webHostEnvironment.WebRootPath, "sliders");
                string uniqueSlider = Guid.NewGuid().ToString().Substring(0, 8) + "_" + anhFile.FileName;
                string SliderPath = Path.Combine(SliderFolder, uniqueSlider);
                using (var fileStream = new FileStream(SliderPath, FileMode.Create))
                {
                    anhFile.CopyTo(fileStream);
                }
                slider.Anh = uniqueSlider;
            }
            if (ModelState.IsValid)
            {
                var response = await _sliderServices.CreateAsync(slider, StaticDetails.SliderAPIPath + "Create");
                if (response)
                {
                    TempData["Success"] = "Thêm mới thành công !";
                }
                else
                {
                    TempData["Error"] = "Đã xảy ra lỗi ...!";
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(slider);
            }

        }
        [HttpGet]
        public async Task<IActionResult> Update(int slideId)
        {
            var slider = await _sliderServices.GetByIdAsync(slideId, StaticDetails.SliderAPIPath + "GetById");
            return View(slider);
        }

        [HttpPost]
        public async Task<IActionResult> Update(SliderViewModel slider, IFormFile anhFile)
        {
            //var sliderUpdate = await _sliderServices.GetByIdAsync(slider.SlideId, StaticDetails.SliderAPIPath + "GetById");
            if (anhFile != null)
            {
                string SliderFolder = Path.Combine(_webHostEnvironment.WebRootPath, "sliders");
                string uniqueSlider = Guid.NewGuid().ToString().Substring(0, 8) + "_" + anhFile.FileName;
                string SliderPath = Path.Combine(SliderFolder, uniqueSlider);
                using (var fileStream = new FileStream(SliderPath, FileMode.Create))
                {
                    anhFile.CopyTo(fileStream);
                }
                slider.Anh = uniqueSlider;
            }
            var response = await _sliderServices.UpdateAsync(slider, StaticDetails.SliderAPIPath + "Update");
            if (response)
            {
                TempData["Success"] = "Cập nhật thành công !";
            }
            else
            {
                TempData["Error"] = "Đã xảy ra lỗi ...!";
            }
            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public async Task<IActionResult> Delete(int slideId)
        {
            var response = await _sliderServices.DeleteAsync(slideId, StaticDetails.SliderAPIPath + "Delete");
            if (response)
            {
                TempData["Success"] = "Xóa thành công !";
            }
            else
            {
                TempData["Error"] = "Đã xảy ra lỗi ...!";
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

TicketBookingOnline.Web/Areas/Admin/Views/Slider/Create.cshtml
@model SliderViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Thêm mới hình quảng cáo</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-area="Admin" asp-controller="Slider" asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ten" class="form-label"></label>
                <input type="text" asp-for="Ten" class="form-control" required/>
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>

            <div class="form-group">
                 <img id="outputAnh" src="~/thumbail/h0.png" width="100%" height="500">
                <input asp-for="Anh" class="form-control" hidden/>
                <input id="anhFile" name="anhFile" type="file" style="margin-top: 5px" required
                       onchange="document.getElementById('outputAnh').src = window.URL.createObjectURL(this.files[0])" />
                <span asp-validation-for="Anh" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Thêm mới" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-info">Trở về</a>
            </div>
        </form>
    </div>
</div>

TicketBookingOnline.Web/Areas/Admin/Views/Slider/Index.cshtml
@model IEnumerable<TicketBookingOnline.ViewModels.Sliders.SliderViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Danh sách hình quảng cáo</h1>
<hr/>
<p>
    <a asp-action="Create" class="btn btn-primary">Thêm mới</a>
</p>
@if (Model.Count() == 0)
{
    <h1>Không có hình quảng cáo nào</h1>
}
else
{
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ten)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anh)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ten)
            </td>
            <td>
                <img style="width:200px" height="130px" src="~/sliders/@item.Anh" alt=@item.Ten />
            </td>
            <td>
                <a class="nav-link text-muted waves-effect waves-dark pro-pic" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-solid fa-pen" style="font-size: x-large; color: darkcyan"></i>
                            </a>
                        <ul class="dropdown-menu dropdown-menu-end user-dd animated" aria-labelledby="navbarDropdown" style="left: -100px">
                            
                                <li>
                                    <a asp-action="Update" asp-route-slideId=@item.SlideId><i class="fa-solid fa-file-pen"></i>&nbsp Chỉnh sửa</a>
                                </li>
                                <li><hr class="dropdown-divider"></li>
                                <li>
                                    <a href="" class="open" data-toggle="modal" data-target="#modalDelete"
                   onclick="document.getElementById('slideId').value=@item.SlideId"><i class="fa-solid fa-trash"></i>&nbsp Xóa</a>
                                </li>
                            </ul>
            </td>
        </tr>
}
    </tbody>
</table>
<!-- Modal Delete -->
<div class="modal fade" id="modalDelete" role="dialog">
    <div class="modal-dialog">
        <form asp-controller="Slider" asp-action="Delete" method="post">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-body">
                    <h4 class="modal-title" style="float: left">Xác nhận xóa</h4>
                    <button type="button" style="float: right" class="close" data-dismiss="modal">&times;</button>
                    <hr />
                    <h3>Bạn chắc chắn muốn xóa hình quảng cáo này?</h3>
                    <input name="slideId" id="slideId" hidden/>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                    <input type="submit" value="Xóa" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>
}

TicketBookingOnline.Web/Areas/Admin/Views/Slider/Update.cshtml
@model SliderViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Cập nhật hình quảng cáo</h1>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-area="Admin" asp-controller="Slider" asp-action="Update" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="SlideId" hidden/>
            <div class="form-group">
                <label asp-for="Ten" class="form-label"></label>
                <input type="text" asp-for="Ten" class="form-control" required/>
                <span asp-validation-for="Ten" class="text-danger"></span>
            </div>

            <div class="form-group">
                <img id="outputAnh" src="~/sliders/@Model.Anh" width="100%" height="500">
                <input asp-for="Anh" class="form-control" hidden></input>
                <input id="anhFile" name="anhFile" type="file" style="margin-top: 5px" 
                       onchange="document.getElementById('outputAnh').src = window.URL.createObjectURL(this.files[0])" />
                <span asp-validation-for="Anh" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Cập nhật" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-info">Trở về</a>
            </div>
        </form>
    </div>
</div>